@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/entries

###

POST {{baseUrl}}/entries
Content-Type: application/json

{
  "text": "Another text",
  "author": "John"
}

###

DELETE {{baseUrl}}/entries
Content-Type: application/json

{
  "_id": "62346aabf32d78531347deb0"
}